# Makefile for libzzt2 in DJGPP

# Choose your compiler & archiver
CC = gcc
AR = ar cqs

RM = rm -f

# Compiling from DOS
DOS = -DDOS

# Compile and link flags
CFLAGS =
LDFLAGS =

# Makefile rules
include libzzt2.make
