# Makefile for libzzt2 in Linux

# Choose your compiler & archiver
CC = gcc
AR = ar cqs

RM = rm -f

# Uncomment when compiling from DOS
DOS = -DDOS

# Compile and link flags
CFLAGS =
LDFLAGS =

# Makefile rules
include libzzt2.make
