# Makefile for libzzt2

# Choose your compiler & archiver
CC = i586-pc-msdosdjgpp-gcc
AR = i586-pc-msdosdjgpp-ar cqs

RM = rm -f

# DOS is on
DOS = -DDOS

# Compile and link flags
CFLAGS =
LDFLAGS =

# Makefile rules
include libzzt2.make
