# Makefile for libzzt2 in Windows

# Choose your compiler & archiver
CC = i686-pc-cygwin-gcc -mno-cygwin
AR = i686-pc-cygwin-ar cqs

RM = rm -f

# Uncomment when compiling from DOS
#DOS = -DDOS

# Compile and link flags
CFLAGS =
LDFLAGS =

# Makefile rules
include libzzt2.make
