# Makefile for libzzt2

# Choose your compiler & archiver
CC = i586-pc-msdosdjgpp-gcc
AR = i586-pc-msdosdjgpp-ar cqs

RM = rm -f

# Uncomment when compiling from DOS
#DOS = -DDOS

CFLAGS = $(OPTIMIZE) $(DOS)

# Compile and link flags
CFLAGS =
LDFLAGS =

# Makefile rules
include libzzt2.make
