# Makefile for synth in DJGPP

# Choose your compiler & archiver
CC = gcc
AR = ar cqs

RM = rm -f

# Compiling from DOS
DOS = ON

# Compile and link flags
CFLAGS =
LDFLAGS =

# Makefile rules
include synth.make
