# Makefile for synth in Windows

# Choose your compiler & archiver
CC = i686-pc-cygwin-gcc -mno-cygwin
AR = i686-pc-cygwin-ar cqs

RM = rm -f

# Compiling with SDL
SDL = ON

# Compile and link flags
CFLAGS =
LDFLAGS =

# Makefile rules
include synth.make
