# Makefile for libzzt2 in Linux

# Choose your compiler & archiver
CC = gcc
AR = ar cqs

RM = rm -f

# Compiling with SDL
SDL = ON

# Compile and link flags
CFLAGS =
LDFLAGS =

# Makefile rules
include synth.make
