# Makefile for synth in DOS (crosscompiled)

# Choose your compiler & archiver
CC = i586-pc-msdosdjgpp-gcc
AR = i586-pc-msdosdjgpp-ar cqs

RM = rm -f

CFLAGS =

# DOS is on
DOS = -DDOS

# Compile and link flags
CFLAGS =
LDFLAGS =

# Makefile rules
include synth.make
