# Makefile for synth in DOS (crosscompiled)

# Choose your compiler & archiver
CC = i586-pc-msdosdjgpp-gcc
AR = i586-pc-msdosdjgpp-ar cqs

RM = rm -f

CFLAGS = $(OPTIMIZE) $(DOS)

# Compile and link flags
CFLAGS =
LDFLAGS =

# Makefile rules
include synth.make
