name: build

on:
  push:
    branches:
#      - main
      - ci
#  pull_request:
#    branches:
#      - main
#    tags:
#      - *

jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        target:
          - appimage
          - dos
          - macos
          - source
          - windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          # build script for ${{ matrix.target }}
          cd inst
          ./build.py ${{ matrix.target }}
      - name: per-target artifact
        uses: actions/upload-artifact@v3
        with:
          name: kevedit-${{ matrix.target }}
          path: inst/dist/*
      - name: combined artifact
        uses: actions/upload-artifact@v3
        with:
          name: all
          path: inst/dist/*
